export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const USER = 'USER';
export const SET_ERROR = 'SET_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
export const LOAD_USER = 'LOAD_USER';
export const LOAD_ERROR = 'LOAD_ERROR';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const USER_DATA = 'USER_DATA';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT= 'EDIT_PRODUCT';
export const NEW_ARRIVALS = 'NEW_ARRIVALS';
export const PRODUCT_INFO = 'PRODUCT_INFO';
export const HOME_CATEGORY = 'HOME_CATEGORY';
export const GET_CART = 'GET_CART';
export const LOGOUT = 'LOGOUT';
export const BANNER = 'BANNER'
export const GET_MAIN_CATEGORY = 'GET_MAIN_CATEGORY';
export const GET_SUB_CATEGORY_PRODUCT = 'GET_SUB_CATEGORY_PRODUCT';
// export const URL = 'http://172.20.10.4:3080'; 
// export const URL = 'http://192.168.43.124:3080'; 
// export const URL = 'https://sleepy-oasis-15614.herokuapp.com';
export const URL = 'https://thefamilyshop.in/api/hooks';
// export const URL = 'http://68.183.92.95/api/hooks'

